// product actions
export const GET_ALL_ICONS_REQUEST = 'GET_ALL_ICONS_REQUEST';
export const GET_ALL_ICONS_SUCCESS = 'GET_ALL_ICONS_SUCCESS';
export const GET_ALL_ICONS_FAIL = 'GET_ALL_ICONS_FAIL';
export const ADD_ICON_TO_PRODUCT = 'ADD_ICON_TO_PRODUCT';
export const UPDATE_BG_COLOR = 'UPDATE_BG_COLOR';
export const SET_ICONS = 'SET_ICONS';
export const LIST_UPLOADED_ICONS = 'LIST_UPLOADED_ICONS';
export const UPDATE_FILTERED_ICONS = 'UPDATE_FILTERED_ICONS';

// alert actions
export const SET_ALERT = 'SET_ALERT';

// upload actions
export const SHOW_UPLOAD_MODAL = 'SHOW_UPLOAD_MODAL';
export const UPLOAD_ICON_TO_LIST_REQUEST = 'UPLOAD_ICON_TO_LIST_REQUEST';
export const UPLOAD_ICON_TO_LIST_SUCCESS = 'UPLOAD_ICON_TO_LIST_SUCCESS';
export const UPLOAD_ICON_TO_LIST_FAIL = 'UPLOAD_ICON_TO_LIST_FAIL';
export const UPLOAD_ICON_TO_LIST_RESET = 'UPLOAD_ICON_TO_LIST_RESET';
export const UPLOAD_ICON_TO_LIST_REMOVE_ERROR_MSG =
  'UPLOAD_ICON_TO_LIST_REMOVE_ERROR_MSG';

// product settings action
export const PRODUCT_SETTINGS_UPDATE = 'PRODUCT_SETTINGS_UPDATE';
export const PRODUCT_SETTINGS_IS_COLOR = 'PRODUCT_SETTINGS_IS_COLOR';
export const PRODUCT_SETTINGS_SEARCH = 'PRODUCT_SETTINGS_SEARCH';
